/**
 *
 * Types of GridderTasks.
 *
 */
export enum EGRIDDERTASKTYPE {
  DISCRETEPOLYAREASUMMARY = "DISCRETEPOLYAREASUMMARY",
  DISCRETEPOLYTOPAREA = "DISCRETEPOLYTOPAREA",
  POINTAGGREGATIONS = "POINTAGGREGATIONS",
  POINTIDWINTERPOLATION = "POINTIDWINTERPOLATION",
  MDTPROCESSING = "MDTPROCESSING"
}
