#!/bin/bash

# ---------------------------
#
# This is for connecting to the cell_raw_data at euler.
#
# ---------------------------
#
# Prefix variables with MLKC_.
#
# ---------------------------

# -----
# Docker
# -----
export MLKC_CELL_NETWORK=

# -----
# Persistence config
# -----
export MLKC_CELL_DB_PASSWORD=$MLKC_CELL_RAW_DATA_DB_PASS
export MLKC_CELL_DB_HOST=$MLKC_37NORTH_HOST
export MLKC_CELL_DB_USER=$MLKC_CELL_RAW_DATA_USER
export MLKC_CELL_DB_PORT=$MLKC_CELL_RAW_DATA_DB_PORT
