#!/bin/bash

# ---------------------------
#
# This is for connecting to the cell_raw_data at euler.
#
# ---------------------------
#
# Prefix variables with MLKC_.
#
# ---------------------------

# -----
# Docker
# -----
export MLKC_CELL_NETWORK=

# -----
# Persistence config
# -----
export MLKC_CELL_DB_PASSWORD=postgres
export MLKC_CELL_DB_HOST=37north.io
export MLKC_CELL_DB_USER=postgres
export MLKC_CELL_DB_PORT=5432
