#!/bin/bash

# ---------------------------
#
# This is for connecting to the cell_raw_data at euler.
#
# ---------------------------
#
# Prefix variables with MLKC_.
#
# ---------------------------

# -----
# Docker
# -----
export MLKC_CELL_NETWORK=

# -----
# Persistence config
# -----
export MLKC_CELL_RAW_DATA_DB_PASSWORD=$MLKC_SYSTEM_CELL_RAW_DATA_DB_PASS
export MLKC_CELL_RAW_DATA_DB_HOST=$MLKC_SYSTEM_CELL_RAW_DATA_HOST_37NORTH
export MLKC_CELL_RAW_DATA_DB_USER=$MLKC_SYSTEM_CELL_RAW_DATA_USER
export MLKC_CELL_RAW_DATA_DB_PORT=$MLKC_SYSTEM_CELL_RAW_DATA_DB_PORT
