#!/bin/bash

# ---------------------------
#
# Common settings for all contexts.
#
# ---------------------------
#
# Prefix variables with MLKC_.
#
# ---------------------------
export MLKC_CELL_APP=cell
export MLKC_CELL_VERSION=1.0.0
export MLKC_CELL_INSTANCE_GENERATION=$(date +"%Y%m%d-%H%M%S")

# -----
# Docker
# -----
export MLKC_CELL_NETWORK=cell
export MLKC_CELL_RAW_DATA_NETWORK=cell_raw_data
export MLKC_CELL_PRODUCTION_IMAGE_ROOT=registry.gitlab.com/malkab-phd/cell
export MLKC_CELL_PRODUCTION_IMAGE_TAG=$MLKC_CELL_VERSION_$MLKC_CELL_INSTANCE_GENERATION

# -----
# Remote SSH
# -----
export MLKC_CELL_SSH_HOST=
export MLKC_CELL_SSH_USER=

# -----
# Node params
# -----
export NODE_MEMORY=20GB
export MLKC_CELL_NODE_ENV=development

# -----
# PG Config for 64GB RAM, 8 CPU, SSD
# This is for PG configuration file, not for the pool
# -----
export MLKC_CELL_PG_MAX_CONNECTIONS=6000
export MLKC_CELL_PG_SHARED_BUFFERS=40GB
export MLKC_CELL_PG_EFFECTIVE_CACHE_SIZE=122GB
export MLKC_CELL_PG_MAINTENANCE_WORK_MEM=2GB
export MLKC_CELL_PG_CHECKPOINT_COMPLETION_TARGET=0.7
export MLKC_CELL_PG_WAL_BUFFERS=16MB
export MLKC_CELL_PG_DEFAULT_STATISTICS_TARGET=500
export MLKC_CELL_PG_RANDOM_PAGE_COST=1.1
export MLKC_CELL_PG_EFFECTIVE_IO_CONCURRENCY=200
export MLKC_CELL_PG_WORK_MEM=332MB
export MLKC_CELL_PG_MIN_WAL_SIZE=512MB
export MLKC_CELL_PG_MAX_WAL_SIZE=2GB
export MLKC_CELL_PG_MAX_WORKER_PROCESSES=8
export MLKC_CELL_PG_MAX_PARALLEL_WORKERS_PER_GATHER=4
export MLKC_CELL_PG_MAX_PARALLEL_WORKERS=8
export MLKC_CELL_PG_MAX_PARALLEL_MAINTENANCE_WORKERS=4

# -----
# PG persistence config for celldb, some items at mlkcontext/system
# -----
export MLKC_CELL_DB_NETWORK=$MLKC_CELL_NETWORK
export MLKC_CELL_DB_HOST=cell-db-postgis-dev
export MLKC_CELL_DB_USER=postgres
export MLKC_CELL_DB_PORT=5432
export MLKC_CELL_DB_PASS=postgres
export MLKC_CELL_DB_DB=cell
export MLKC_CELL_DB_DOCKER_EXTERNAL_PORT=5600
export MLKC_CELL_DB_MAXPOOLSIZE=2000
export MLKC_CELL_DB_MINPOOLSIZE=5
export MLKC_CELL_DB_IDLETIMEOUTMILLIS=60000

# -----
# PG persistence config for cell_raw_data, some items at mlkcontext/system
# -----
export MLKC_CELL_RAW_DATA_NETWORK=
export MLKC_CELL_RAW_DATA_HOST=$MLKC_SYSTEM_37NORTH_HOST
export MLKC_CELL_RAW_DATA_USER=$MLKC_SYSTEM_37NORTH_PG_USER
export MLKC_CELL_RAW_DATA_PORT=$MLKC_SYSTEM_37NORTH_PG_PORT
export MLKC_CELL_RAW_DATA_PASS=$MLKC_SYSTEM_37NORTH_PG_PASS
export MLKC_CELL_RAW_DATA_DB=cell_raw_data
export MLKC_CELL_RAW_DATA_DOCKER_EXTERNAL_PORT=5700
export MLKC_CELL_RAW_DATA_MAXPOOLSIZE=2000
export MLKC_CELL_RAW_DATA_MINPOOLSIZE=5
export MLKC_CELL_RAW_DATA_IDLETIMEOUTMILLIS=60000

# -----
# Redis persistence config, some items at mlkcontext/system
# -----
# Remember that for RxRedis clients this must be used as redis://whatever, but
# not here
export MLKC_CELL_REDIS_URL=cell-redis
export MLKC_CELL_REDIS_PASSWORD=$MLKC_SYSTEM_CELL_REDIS_PASS
export MLKC_CELL_REDIS_DOCKER_EXTERNAL_PORT=6700
export MLKC_CELL_REDIS_PORT=6379
