#!/bin/bash

# ---------------------------
#
# This config is for launching the gridding scripts on localhost / 37north.io
# in test mode.
#
# ---------------------------
#
# Prefix variables with MLKC_.
#
# ---------------------------
# -----
# Node params
# -----
export NODE_MEMORY=200GB
export MLKC_CELL_NODE_ENV=development

# -----
# PG persistence config for celldb, some items at mlkcontext/system
# -----
export MLKC_CELL_DB_NETWORK=$MLKC_CELL_NETWORK
export MLKC_CELL_DB_HOST=localhost
export MLKC_CELL_DB_USER=postgres
export MLKC_CELL_DB_PORT=5600
export MLKC_CELL_DB_PASS=postgres
export MLKC_CELL_DB_DB=cell
export MLKC_CELL_DB_DOCKER_EXTERNAL_PORT=5600
export MLKC_CELL_DB_MAXPOOLSIZE=2000
export MLKC_CELL_DB_MINPOOLSIZE=5
export MLKC_CELL_DB_IDLETIMEOUTMILLIS=60000

# -----
# PG persistence config for cell_raw_data, some items at mlkcontext/system
# -----
export MLKC_CELL_RAW_DATA_NETWORK=
export MLKC_CELL_RAW_DATA_HOST=$MLKC_SYSTEM_37NORTH_HOST
export MLKC_CELL_RAW_DATA_USER=$MLKC_SYSTEM_37NORTH_PG_USER
export MLKC_CELL_RAW_DATA_PORT=$MLKC_SYSTEM_37NORTH_PG_PORT
export MLKC_CELL_RAW_DATA_PASS=$MLKC_SYSTEM_37NORTH_PG_PASS
export MLKC_CELL_RAW_DATA_DB=cell_raw_data
export MLKC_CELL_RAW_DATA_DOCKER_EXTERNAL_PORT=5700
export MLKC_CELL_RAW_DATA_MAXPOOLSIZE=2000
export MLKC_CELL_RAW_DATA_MINPOOLSIZE=5
export MLKC_CELL_RAW_DATA_IDLETIMEOUTMILLIS=60000
