FROM nginx

LABEL author="Juan Pedro Perez"
LABEL email="jp.perez.alcantara@gmail.com"

# Environment
ENV NODE_ENV "production"
ENV VERSION "##VERSION##"

# Copy app code
COPY assets/ /usr/share/nginx/html/

# Expose ports
EXPOSE 80
