version: '3.5'

networks:
  sunnsaas_v1_production_test:
    name: sunnsaas_v1_production_test
    external: false
    attachable: true

volumes:
  sunnsaas_v1_production_test-postgis:
    name: sunnsaas_v1_production_test-postgis
  sunnsaas_v1_production_test-redis:
    name: sunnsaas_v1_production_test-redis
  sunnsaas_v1_production_test-fee:
    name: sunnsaas_v1_production_test-fee
  sunnsaas_v1_production_test-uploads:
    name: sunnsaas_v1_production_test-uploads
  sunnsaas_v1_production_test-logs:
    name: sunnsaas_v1_production_test-logs
  sunnsaas_v1_production_test-logs-workers:
    name: sunnsaas_v1_production_test-logs_workers
  sunnsaas_v1_production_test-temp:
    name: sunnsaas_v1_production_test-temp
  sunnsaas_v1_production_test-fortran:
    name: sunnsaas_v1_production_test-test_fortran

services:
  postgis:
    image: registry.gitlab.com/sunnsaas/sunnsaas_v1/pg:latest

    environment:
      - PASSWORD=${MLKC_SUNNSAAS_DB_PASSWORD}

    networks:
      - sunnsaas_v1_production_test

    ports:
      - "5850:5432"

    volumes:
      - sunnsaas_v1_production_test-postgis:/data

  redis:
    image: registry.gitlab.com/sunnsaas/sunnsaas_v1/redis:latest

    networks:
      - sunnsaas_v1_production_test

    ports:
      - "6800:6379"

    volumes:
      - sunnsaas_v1_production_test-redis:/data

  api:
    image: registry.gitlab.com/sunnsaas/sunnsaas_v1/api:latest
    depends_on:
      - postgis
      - redis

    networks:
      - sunnsaas_v1_production_test

    ports:
      - "${MLKC_SUNNSAAS_API_OUTER_PORT}:8080"

    volumes:
      - sunnsaas_v1_production_test-fee:/fee
      - sunnsaas_v1_production_test-uploads:/uploads
      - sunnsaas_v1_production_test-logs:/logs
      - sunnsaas_v1_production_test-temp:/temp
      - sunnsaas_v1_production_test-logs-workers:/worker_logs

    environment:
      - MLKC_SUNNSAAS_NODE_ENV="production"
      - MLKC_SUNNSAAS_VERSION=${MLKC_SUNNSAAS_VERSION}
      - MLKC_SUNNSAAS_BUILD=${MLKC_SUNNSAAS_BUILD}
      - MLKC_SUNNSAAS_NODE_MEMORY=${MLKC_SUNNSAAS_NODE_MEMORY}
      - MLKC_SUNNSAAS_DB_HOST=${MLKC_SUNNSAAS_DB_HOST}
      - MLKC_SUNNSAAS_DB_INNER_PORT=5432
      - MLKC_SUNNSAAS_DB_USER=${MLKC_SUNNSAAS_DB_USER}
      - MLKC_SUNNSAAS_DB_PASSWORD=${MLKC_SUNNSAAS_DB_PASSWORD}
      - MLKC_SUNNSAAS_DB_DB=${MLKC_SUNNSAAS_DB_DB}
      - MLKC_SUNNSAAS_DB_MAXPOOLSIZE=${MLKC_SUNNSAAS_DB_MAXPOOLSIZE}
      - MLKC_SUNNSAAS_DB_MINPOOLSIZE=${MLKC_SUNNSAAS_DB_MINPOOLSIZE}
      - MLKC_SUNNSAAS_REDIS_URL=${MLKC_SUNNSAAS_REDIS_URL}
      - MLKC_SUNNSAAS_REDIS_PASSWORD=${MLKC_SUNNSAAS_REDIS_PASSWORD}
      - MLKC_SUNNSAAS_JWT_ACCESS_TOKEN_SECRET=${MLKC_SUNNSAAS_JWT_ACCESS_TOKEN_SECRET}
      - MLKC_SUNNSAAS_JWT_REFRESH_TOKEN_SECRET=${MLKC_SUNNSAAS_JWT_REFRESH_TOKEN_SECRET}
      - MLKC_SUNNSAAS_JWT_ACCESS_TOKEN_LIFESPAN=${MLKC_SUNNSAAS_JWT_ACCESS_TOKEN_LIFESPAN}
      - MLKC_SUNNSAAS_JWT_REFRESH_TOKEN_LIFESPAN=${MLKC_SUNNSAAS_JWT_REFRESH_TOKEN_LIFESPAN}
      - MLKC_SUNNSAAS_SYSTEM_STATUS_INTERVAL=${MLKC_SUNNSAAS_SYSTEM_STATUS_INTERVAL}
      - MLKC_SUNNSAAS_DELETE_CONFIG_FILE=${MLKC_SUNNSAAS_DELETE_CONFIG_FILE}
